// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/36e2ea37c5b57e0eaa7f2cddf52a1fa255a8b8f3/redux-devtools/redux-devtools.d.ts
declare module "redux-devtools" {
  import * as React from 'react'

  interface IDevTools {
    new (): JSX.ElementClass
    instrument(): Function
  }

  export function createDevTools(el: React.ReactElement<any>): IDevTools
  export function persistState(debugSessionKey: string): Function

  var factory: { instrument(): Function }

  export default factory;
}