// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/d036b5253c1ef89d4e3310516d2fa2117d0db555/react-tap-event-plugin/react-tap-event-plugin.d.ts
declare module 'react-tap-event-plugin'{
    var exports:()=>any;
    export = exports;
}