// constants.js
exports.mapheader = ['_COLUMNS_','Category:NAME,Category:CODE,Note:DESCRIPTION,Count:VALUE']

exports.META_START = '_META_START_'
exports.META_END = '_META_END_'
exports.COLUMNS_CATEGORIES = 'COLUMNS_CATEGORIES'
exports.COLUMNS_ATTRIBUTES = 'COLUMNS_ATTRIBUTES'
exports.NAME = 'NAME'
exports.CODE = 'CODE'
exports.DESCRIPTION = 'DESCRIPTION'
exports.INTAKE_DATETIME = 'INTAKE_DATETIME'
exports.TOTAL_AMOUNT = 'TOTAL_AMOUNT'
exports.COLUMNS = '_COLUMNS_'
exports.UNITS_CODE = 'UNITS_CODE'
exports.UNITS_MULTIPLIER = 'UNITS_MULTIPLIER'
