// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/d036b5253c1ef89d4e3310516d2fa2117d0db555/react-tap-event-plugin/react-tap-event-plugin.d.ts
// Type definitions for react-tap-event-plugin
// Project: https://github.com/zilverline/react-tap-event-plugin
// Definitions by: Michael Ledin <https://github.com/mxl>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

declare module 'react-tap-event-plugin'{
    var exports:()=>any;
    export = exports;
}