// helpcontent.tsx
// copyright (c) 2016 Henrik Bechmann, Toronto, MIT Licence
// explorerbranch.tsx

import * as React from 'react'
import {Card, CardTitle, CardText} from 'material-ui/Card'
import SvgIcon from 'material-ui/SvgIcon'
import FontIcon from 'material-ui/FontIcon'

let content = 
<div>
<Card>
    <CardText>
    The best way to become familiar with the explorer is to <span style={{fontStyle:'italic'}}>play with it</span> (experiment).
    Once in a while, review the lists below. Click on any title below for details.
    </CardText>
</Card>
<Card>
    <CardTitle
        actAsExpander={true}
        showExpandableButton={true} >
        Dataset Options
    </CardTitle>
    <CardText expandable style={{paddingTop:"0px"}}>
    <p>There are several dataset options available for charts:</p>
    <dl>
        <dt><strong>Viewpoint</strong></dt>
        <dd> a viewpoint is a classification scheme (taxonomy) of a set of accounts. 
        </dd>
        <dt><strong>Source</strong></dt>
        <dd>alternate detailed datasets available for the selected Viewpoint (see the Budgetpedia
            project's <a target = "_blank" href="https://drive.google.com/drive/u/0/folders/0B208oCU9D8OuM2NmUk9XR1VCbEU">research repository)</a></dd>
        <dt><strong>Aspect</strong></dt>
        <dd> particular aspects of the dataset, such as Revenue, Expenses or Staffing</dd>
        <dt><strong>Prorated</strong></dt>
        <dd> the beginnings of diagnostic analytics, using simple math to view the 
            data compared with relevant related metrics, such as per person or per household</dd>
        <dt><strong>Inflation adjusted</strong></dt>
        <dd> the datasets are updated annually to reflect the Bank of 
            Canada's Inflation Calculator. This makes it possible to get historical perspectives that are
            meaningful in today's dollar terms.
        </dd>
    </dl>
    <p>Choices for the selections are interdependent. Toronto budgets have similar classifications for 
        Revenue and Expenses for example, and therefore these can be viewed together. Financial statements 
        on the other hand do not have similar classifications for Revenue and Expenses.
    </p>

    <hr />

    <p><strong><em>Viewpoint</em></strong> choices include:</p>
    <dl>
        <dt><strong>Functional (operating budgets)</strong></dt>
        <dd>combines City of Toronto Agencies and Divisions into groups according to the nature of 
            the services delivered (this is the default). The classification scheme above the 
            Division/Agency level was developed by Budgetpedia project contributors.
        </dd>
        <dt><strong>Structural (operating budgets)</strong></dt>
        <dd>more traditional: separates Agencies from Divisions, and generally by organizational
            structures. Groupings are closer to those found in City annual Budget Summaries.</dd>
        <dt><strong>Audited Expenses, and Audited Revenues</strong></dt>
        <dd>
            These reporting structures are manadated by the province (and GAAP -- Generally Accepted
            Accounting Principles). They are functional, and are comparable to other municipalities in the 
            province. Summary groupings above the statment levels are added by the Budgetpedia project
            for easier access.
        </dd>
        <dt><strong>Audited Expenses by Object</strong></dt>
        <dd>
            Expenses by Object is a restatement of expenses by object of expenditure, such as materials,
            or Wages & Salaries. These categories cross all Divisions and Agencies, and therefore provide a 
            general picture of the ways that money is spent.
        </dd>
    </dl>

    <hr />

    <p>
        <strong><em>Source</em></strong> choices depend on the Viewpoint that is chosen.
    </p>

    <dl>

    <dt><em>For Viewpoint = Budget (both functional and structural), Versions</em> include:</dt>
    <dd>
        <dl>
        <dt><strong>Summary PDF Reports 2003 - 2016</strong></dt>
        <dt><strong>Detailed open data files 2011 - 2016</strong></dt>
        <dt><strong>Variance Reports</strong> <em>[deferred]</em></dt>
        </dl>
    </dd>
    <dd>The detailed files are generated by <em>PBFT</em> which stands for <em>Public Budget Formulation Tool</em> which is part of the City's new
        FPARS (Financial Planning Analysis and Reporting System) system
    </dd>

    <dt style={{marginTop:"20px"}}><em>For Viewpoint = Audited Expenses or Revenues, Source</em> includes:</dt>
    <dd>
        <dl>
        <dt><strong>Audited Statements 1998 - 2015</strong></dt>
        <dt><strong>to come: Financial Information Returns</strong></dt>
        </dl>
    </dd>
    <dd>
        FIR for MMAH = Financial Information Returns for the Ontario Ministry of Municipal Affairs 
        and Housing.
    </dd>
    </dl>
    <hr />

    <p>
        <strong><em>Aspect</em></strong> choices depend on the Viewpoint and Version that is chosen.
    </p>
    <dl>

        <dt><em>For Viewpoint = Budget (both functional and structural), Version = Summary or Detailed, 
            Aspects</em> include:
        </dt>

        <dd>
            <dl>
            <dt><strong>Revenue</strong></dt>
            <dt><strong>Expenses</strong></dt>
            <dt><strong>Staffing</strong></dt>
            </dl>

        </dd>
        <dd> All of these are based on City documents which have similar line items across all aspects. This 
            makes the figures from all sources comparable.
        </dd>
        <dt style={{marginTop:"20px"}}><em>For Viewpoint = Consolidated Statements, any Version, Aspects</em> include:</dt>
        <dd>
            <dl>
                <dt><strong>Revenue (actual), or</strong></dt>
                <dt><strong>Expenses (actual)</strong></dt>
            </dl>

        </dd>
        <dd>The classification schemes for these are different for each, and therefore they cannot be 
            combined.
        </dd>
        <dt style={{marginTop:"20px"}}><em>For Viewpoint = Expenses by Object, Source = 
            Audited Statements, Aspects</em> include:
        </dt>
        <dd>
            <dl>
                <dt><strong>Expenses</strong></dt>
            </dl>
        </dd>
        <dd>These come from notes to the audited financial statements.
        </dd>

    </dl>
    <hr />

    <p>
        <strong><em>Prorated</em></strong> choices are common for all other choices, and include:
    </p>
    <dl>
        <dd>
            <dl>
                <dt><strong>Population: per person</strong></dt>
                <dt><strong>Population: per 100,000 people</strong></dt>
                <dt><strong>Per household</strong></dt>
                <dt><strong>Per 40,000 households</strong></dt>
                <dt><strong>Per Ward (x 44)</strong> an average per ward</dt>
                <dt><strong>Per Neighbourhood (x 4 x 44)</strong> an average per neighbourhood, 4 per ward, about walking distance</dt>
            </dl>
        </dd>
    </dl>

    <hr />

    <p>
        <strong><em>Inflation adjusted</em></strong> is on by default, but can be turned off.</p>
   <dl>
   <dd>This uses
        the Statistics Canada's estimated CPI for Toronto, to adjust historical figures in terms of recent 
        currency valuations, for more meaningful trend analysis.
    </dd>
    </dl>
    </CardText>

</Card>
<Card>
    <CardTitle
        actAsExpander={true}
        showExpandableButton={true} >
        Chart Options
    </CardTitle>
    <CardText expandable style={{paddingTop:"0px"}}>
    <p> Chart options vary according to the time options selected. The time options available are:</p>
    <dl>
    <dt><SvgIcon style={
        {
            height:"18px",
            width:"18px", 
            padding:"0 3px",
            border:"1px solid silver", 
            borderRadius:"5px",
            verticalAlign:"middle"
        }
    } viewBox = "0 0 36 36" >
            <rect x="13" y="13" width="10" height="10" />
        </SvgIcon> One year (default)</dt>
    <dd> Select a specific year to investigate.
    </dd>
    <dt><SvgIcon style={
        {
            height:"18px",
            width:"18px", 
            padding:"0 3px",
            border:"1px solid silver", 
            borderRadius:"5px",
            verticalAlign:"middle"
        }
    }  viewBox = "0 0 36 36" >
          <rect x="4" y="13" width="10" height="10" />
          <rect x="22" y="13" width="10" height="10" />
        </SvgIcon> Two years</dt><dd> Allows data for two years to be presented side by side for comparison.
    </dd>
    <dt><SvgIcon style={
        {
            height:"18px",
            width:"18px", 
            padding:"0 3px",
            border:"1px solid silver", 
            borderRadius:"5px",
            verticalAlign:"middle"
        }
    }  viewBox = "0 0 36 36" >
            <ellipse cx="6" cy="18" rx="4" ry="4"/>
            <ellipse cx="18" cy="18" rx="4" ry="4"/>
            <ellipse cx="30" cy="18" rx="4" ry="4"/>
        </SvgIcon> All years (all available years)</dt><dd> Shows all available years to investigate trends.
    </dd>
    </dl>
    <p>Specific years can be selected in the selection dropdowns under the charts.</p>

    <hr />

    <dl>
    <dt><SvgIcon style={
        {
            height:"18px",
            width:"18px", 
            padding:"0 3px",
            border:"1px solid silver", 
            borderRadius:"5px",
            verticalAlign:"middle"
        }
    } viewBox = "0 0 36 36" >
            <rect x="13" y="13" width="10" height="10" />
        </SvgIcon> Chart options when one year is chosen include:</dt>
        <dd>
        <dl>
        <dt><FontIcon style={
            {
                height:"18px", 
                width:"18px",
                padding:"0 3px",
                border:"1px solid silver", 
                borderRadius:"5px",
                verticalAlign:"middle",
                fontSize:"18px",
            }
        } className="material-icons">insert_chart</FontIcon> Column Chart</dt>
        <dd> This shows the basics
            of the components of the chart. Float the mouse over the column to see the number,
            or click on a column to drill down.</dd>
        <dt><FontIcon style={
            {
                height:"18px", 
                width:"18px",
                padding:"0 3px",
                border:"1px solid silver", 
                borderRadius:"5px",
                verticalAlign:"middle",
                fontSize:"18px",
            }
        }
        className="material-icons">donut_small</FontIcon> Donut Chart</dt>
        <dd> This shows the percentages of each
        number in relation to the whole.</dd>
        </dl>
        </dd>
    </dl>

        <hr />

    <dl>
    <dt><SvgIcon style={
        {
            height:"18px",
            width:"18px", 
            padding:"0 3px",
            border:"1px solid silver", 
            borderRadius:"5px",
            verticalAlign:"middle"
        }
    } viewBox = "0 0 36 36" >
          <rect x="4" y="13" width="10" height="10" />
          <rect x="22" y="13" width="10" height="10" />
        </SvgIcon> Chart options when two years is chosen include:</dt>
    <dd>
        <dl>
        <dt><FontIcon style={
            {
                height:"18px", 
                width:"18px",
                padding:"0 3px",
                border:"1px solid silver", 
                borderRadius:"5px",
                verticalAlign:"middle",
                fontSize:"18px",
            }
        } className="material-icons">insert_chart</FontIcon> Column Chart</dt><dd> This offers
        a difference chart. The light colored bars are background bars.</dd>
        <dt><FontIcon style={
            {
                height:"18px", 
                width:"18px",
                padding:"0 3px",
                border:"1px solid silver", 
                borderRadius:"5px",
                verticalAlign:"middle",
                fontSize:"18px",
            }
        }
        className="material-icons">donut_small</FontIcon> A piechart difference chart</dt>
        <dd> This shows the differences
        between the two years chosen.</dd>
        </dl>
    </dd>
    </dl>
    <hr />

    <dl>
    <dt><SvgIcon style={
        {
            height:"18px",
            width:"18px", 
            padding:"0 3px",
            border:"1px solid silver", 
            borderRadius:"5px",
            verticalAlign:"middle"
        }
    } viewBox = "0 0 36 36" >
            <ellipse cx="6" cy="18" rx="4" ry="4"/>
            <ellipse cx="18" cy="18" rx="4" ry="4"/>
            <ellipse cx="30" cy="18" rx="4" ry="4"/>
        </SvgIcon> Chart options when all years is chosen include:</dt>
    <dd>
        <dl>
        <dt><FontIcon style={
            {
                height:"18px", 
                width:"18px",
                padding:"0 3px",
                border:"1px solid silver", 
                borderRadius:"5px",
                verticalAlign:"middle",
                fontSize:"18px",
            }
        }
        className="material-icons">timeline</FontIcon> Line Chart</dt>
        <dd> Basic time lines</dd>
        <dt><SvgIcon style={
        {
            height:"18px",
            width:"18px", 
            padding:"0 3px",
            border:"1px solid silver", 
            borderRadius:"5px",
            verticalAlign:"middle"
        }}>
            <path d="M20,6c0-0.587-0.257-1.167-0.75-1.562c-0.863-0.69-2.121-0.551-2.812,0.312l-2.789,3.486L11.2,6.4  c-0.864-0.648-2.087-0.493-2.762,0.351l-4,5C4.144,12.119,4,12.562,4,13v3h16V6z"/>
            <path d="M20,19H4c-0.552,0-1,0.447-1,1s0.448,1,1,1h16c0.552,0,1-0.447,1-1S20.552,19,20,19z"/>
        </SvgIcon> Area Chart</dt>
        <dd> Same data as timelines, but stacked.</dd>
        <dt><FontIcon style={
            {
                height:"18px", 
                width:"18px",
                padding:"0 3px",
                border:"1px solid silver", 
                borderRadius:"5px",
                verticalAlign:"middle",
                fontSize:"18px",
            }
        } className="material-icons">view_stream</FontIcon> Proportional Chart </dt>
        <dd> All lines add to 100%; 
            individual amounts are shown in proportion to the whole.</dd>
        </dl>
        </dd>
        </dl>
    </CardText>
</Card>
<Card>
    <CardTitle
        actAsExpander={true}
        showExpandableButton={true} >
        Context Options
    </CardTitle>
    <CardText expandable style={{paddingTop:"0px"}}>
    <p> Context options are offered to provide contextual information for the data being viewed, and
    to afford the reader the opportunity to contribute to the process surrounding the budget. These
    are the options offered, found under each chart:</p>
    <dl>
        <dt><FontIcon 
            style={
                {
                    height:"18px", 
                    width:"18px",
                    padding:"0 3px",
                    border:"1px solid silver", 
                    borderRadius:"5px",
                    verticalAlign:"middle",
                    fontSize:"18px",
                }
            }
            className="material-icons">info_outline
            </FontIcon> The <em>information</em> icon 
        </dt>
        <dd><em>[deferred]</em> invokes a dialog containing information related to the current
            data. This could be brief explanations, links to related information, or links to websites
            which specialize in the subject matter. The idea is to allow the reader to discover more context 
            and detail about the subject matter at hand.
        </dd>
        <dt><FontIcon 
            style={
                {
                    height:"18px", 
                    width:"18px",
                    padding:"0 3px",
                    border:"1px solid silver", 
                    borderRadius:"5px",
                    verticalAlign:"middle",
                    fontSize:"18px",
                }
            }
            className="material-icons">note</FontIcon> The <em>notes</em> icon
        </dt>
        <dd><em>[deferred]</em> invokes detailed technical information about the 
            data presented, including source documents, exceptions, errors, and any relevant notes about the
            way the data was processed. If there are errors or exceptions in place, the note icon changes
            colour to red or orange, depending on severity.
        </dd>
        <dt><FontIcon 
            style={
                {
                    height:"18px", 
                    width:"18px",
                    padding:"0 3px",
                    border:"1px solid silver", 
                    borderRadius:"5px",
                    verticalAlign:"middle",
                    fontSize:"18px",
                }
            }
            className="material-icons">share</FontIcon> The <em>share</em> icon </dt> 
            <dd><em>[deferred]</em> provides access to relevant social media
            sites, to allow readers to read or contribute to discussion about the subject at hand.
        </dd>
        <dt><FontIcon 
            style={
                {
                    height:"18px", 
                    width:"18px",
                    padding:"0 3px",
                    border:"1px solid silver", 
                    borderRadius:"5px",
                    verticalAlign:"middle",
                    fontSize:"18px",
                }
            }
            className="material-icons">announcement</FontIcon> The <em>announcement</em> icon 
        </dt>
        <dd><em>[deferred]</em> provides the user with 
            lists of calls to actions or meetings related to the subject matter, or to contribute their own
            call to action or meetings.
        </dd>
        <dt><FontIcon 
            style={
                {
                    height:"18px", 
                    width:"18px",
                    padding:"0 3px",
                    border:"1px solid silver", 
                    borderRadius:"5px",
                    verticalAlign:"middle",
                    fontSize:"18px",
                }
            }
            className="material-icons">view_list</FontIcon> The <em>data</em> icon 
        </dt>
        <dd><em>[deferred]</em> brings up the data underlying the currently viewed chart, with an option to download same.
        </dd>
        <dt><FontIcon 
            style={
                {
                    height:"18px", 
                    width:"18px",
                    padding:"0 3px",
                    border:"1px solid silver", 
                    borderRadius:"5px",
                    verticalAlign:"middle",
                    fontSize:"18px",
                }
            }
            className="material-icons">swap_horiz</FontIcon> The <em>harmonize</em> icon 
        </dt>
        <dd> allows the user to impose the 
            settings made in the current chart onto the other charts in the row (<em>Exhibit</em>).
        </dd>
    </dl>
    </CardText>
</Card>
<Card>
    <CardTitle
        actAsExpander={true}
        showExpandableButton={true} >
        Cloning Features
    </CardTitle>
    <CardText expandable style={{paddingTop:"0px"}}>
    <p>The Budget Explorer organizes charts into horizontal drill-down sequences which we 
    call <em>Exhibits</em>. We allow for cloning and re-ordering these exhibits to allow for comparison,
    exploration, and publication. This clone contains all the option controls of the original. The
    clone is independent of the original.</p>
    <dl>
        <dt><FontIcon 
            style={
                {
                    height:"18px", 
                    width:"18px",
                    padding:"0 3px",
                    border:"1px solid silver", 
                    borderRadius:"5px",
                    verticalAlign:"middle",
                    fontSize:"18px",
                }
            }
            className="material-icons">add_circle_outline</FontIcon> Add a clone of the current Exhibit
        </dt>
        <dd>This icon when invoked adds a clone of the current row of charts below the current row. <em>
            The clone reproduces all of the components and selections of the current
            row.
        </em></dd>
        <dt><FontIcon 
            style={
                {
                    height:"18px", 
                    width:"18px",
                    padding:"0 3px",
                    border:"1px solid silver", 
                    borderRadius:"5px",
                    verticalAlign:"middle",
                    fontSize:"18px",
                }
            }
            className="material-icons">remove_circle_outline</FontIcon> Remove the current Exhibit
        </dt>
        <dd>This icon when invoked removes the current row of charts (cannot currently be undone).</dd>
        <dt><FontIcon 
            style={
                {
                    height:"18px", 
                    width:"18px",
                    padding:"0 3px",
                    border:"1px solid silver", 
                    borderRadius:"5px",
                    verticalAlign:"middle",
                    fontSize:"18px",
                }
            }
            className="material-icons">arrow_upward</FontIcon> Move the current Exhibit up one position
        </dt>
        <dd>When mulitple rows (<em>Exhibits</em>) exist, they can be re-ordered. The up arrow icon
        (to the upper right of the row title) moves the row up one position.</dd>
        <dt><FontIcon 
            style={
                {
                    height:"18px", 
                    width:"18px",
                    padding:"0 3px",
                    border:"1px solid silver", 
                    borderRadius:"5px",
                    verticalAlign:"middle",
                    fontSize:"18px",
                }
            }
            className="material-icons">arrow_downward</FontIcon> Move the current Exhibit down one position
        </dt>
        <dd>When mulitple rows (<em>Exhibits</em>) exist, they can be re-ordered. The down arrow icon
        (to the upper right of the row title) moves the row down one position.</dd>
    </dl>
    </CardText>
</Card>
<Card>
    <CardTitle
        actAsExpander={true}
        showExpandableButton={true} >
        Actionable Features
    </CardTitle>    
    <CardText expandable style={{paddingTop:"0px"}}>
        <p>We've provided a few actionable features to help you find and share charts with friends and associates.</p>

        <dl>
        <dt>Find</dt>
        <dd>This lets you find a chart by the title of the City account, or classification, that it highlights. Enter a key word that is likely to be found in a name.</dd>
        <dt>Share</dt>
        <dd>This gives you a bitly (short) url that you can share with friends. When they go to that url, it will reproduce the current row of charts for them. A good basis for discussion.</dd>
        <dt>Sources</dt>
        <dd>This provides a list of the source reports used to collect the data for the current viewpoint.</dd>
        <dt>Printing charts</dt>
        <dd>To print charts, turn off options on each row of charts to remove clutter, and then use
        a browser utility like Fireshot for Chrome to print the entire visible page.</dd>
        </dl>
    </CardText>
</Card>
</div>

export default content