// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/1da639a106527e0c4010b354a1efe52a3059a291/react-spinkit/react-spinkit.d.ts
// Type definitions for react-spinkit 1.1.4
// Project: https://github.com/KyleAMathews/react-spinkit
// Definitions by: Qubo <https://github.com/tkqubo>
// Definitions: https://github.com/borisyankov/DefinitelyTyped


declare module "react-spinkit" {
    import { Component } from 'react';

    interface Props {
        spinnerName?: string;
    }

    class Spinner extends Component<Props, {}> { }

    export default Spinner;
}