"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const React = require("react");
const Card_1 = require("material-ui/Card");
var { Component } = React;
class Announcements extends Component {
    render() {
        return React.createElement("div", null,
            React.createElement(Card_1.Card, null,
                React.createElement(Card_1.CardTitle, { title: "Budgetpedia Project Announcements" }),
                React.createElement(Card_1.CardText, null,
                    React.createElement("h3", null, "Key Upcoming Events"),
                    React.createElement("ul", { style: { marginBottom: "16px" } },
                        React.createElement("li", null,
                            React.createElement("p", null,
                                React.createElement("strong", null, "Regular Meetups: First Tuesday of each month 6:30-9:00 pm "),
                                React.createElement("br", null),
                                React.createElement("em", null, " Location:"),
                                " ",
                                React.createElement("a", { target: "_blank", href: "http://www.meetup.com/Civic-Tech-Toronto/" }, "Varies - Check the Meetup page for the next meeting")),
                            React.createElement("p", null, "Additional meetings may be scheduled. This is where Budgetpedia was born and raised to its current early state. It's also where a lot of the brainstorming, development and creative processes happen. Anyone with an interest in this project is welcome.  No coding or technical skills required!"),
                            React.createElement("p", null,
                                "For more details, check out the ",
                                React.createElement("a", { href: "./teams" }, "Teams"),
                                " page of this website, or the ",
                                React.createElement("a", { target: "_blank", href: "http://www.civictech.ca" }, "Civic Tech website home Page"),
                                ".")))),
                React.createElement(Card_1.CardText, null,
                    React.createElement("h3", null, "Key Past Events"),
                    React.createElement("ul", { style: { marginBottom: "16px" } },
                        React.createElement("li", null,
                            React.createElement("p", null,
                                React.createElement("strong", null,
                                    "Saturday, April 22, 2017 gave \"lightening\" (5 minute) talk at  ",
                                    React.createElement("a", { target: "_blank", href: "http://investinginto.ca/" }, "Investing in Toronto"),
                                    " consultation"),
                                ". See the ",
                                React.createElement("a", { target: "_blank", href: "https://drive.google.com/open?id=1lVWW_w7BxufjRO8s2oNKi_We9ad9uzMZfEfMJ12ZYvg" }, "slide deck"),
                                "."),
                            React.createElement("p", null,
                                "Highlighted waht we learned like ",
                                React.createElement("em", null, "taxonomies, trends, motivations"),
                                ".")),
                        React.createElement("li", null,
                            React.createElement("p", null,
                                React.createElement("strong", null,
                                    "Saturday, Feb 25, 2017 gave \"lightening\" (10 minute) talk at  ",
                                    React.createElement("a", { target: "_blank", href: "http://hellocon.net/" }, "Hello Con"),
                                    " conference"),
                                ". See the ",
                                React.createElement("a", { target: "_blank", href: "https://www.youtube.com/watch?v=Pn4l9JA1ROg" }, "video"),
                                "."),
                            React.createElement("p", null,
                                "Highlighted benefits of ",
                                React.createElement("em", null, "taxonomies, careful data preparation, and reactive programming"),
                                ". See the slide deck ",
                                React.createElement("a", { target: "_blank", href: "https://drive.google.com/open?id=13tOAln9YE6DOKP_zrGiLzVpeIaZLkd3bWxoBhHj3UUg" }, "here"),
                                ".")),
                        React.createElement("li", null,
                            React.createElement("p", null,
                                React.createElement("strong", null,
                                    "Monday, Feb 6, 2017 honoured to give budget overview presentation to the ",
                                    React.createElement("a", { target: "_blank", href: "http://thetyc.ca/" }, "toronto youth cabinet"),
                                    " budget meeting at City Hall.")),
                            React.createElement("p", null,
                                "Great conversation ensued between councillors Perks, Wong-Tam, and youth cabinet. Our take: people's narratives need to snowball to overcome obstacles. Slide deck we used is ",
                                React.createElement("a", { target: "_blank", href: "https://drive.google.com/open?id=153RdCnnAlNPGMo7_Ji-V4j_nMFczzgdHWELiyI2cYX0" }, "here"),
                                ".")),
                        React.createElement("li", null,
                            React.createElement("p", null,
                                React.createElement("strong", null, "Monday, January 30, 2017 Budgetpedia upgrade v0.1.2 released"),
                                React.createElement("br", null),
                                "This release adds two new features to the explorer page."),
                            React.createElement("p", null,
                                " ",
                                React.createElement("em", null, "Latest analyst notes"),
                                " provides access to the latest city capital and operating analyst notes for all divisions and agencies cited in the budget. These are available from a button at the top of the page, and also from info buttons on all budget charts."),
                            React.createElement("p", null,
                                "Secondly a ",
                                React.createElement("em", null, "View"),
                                " button beside the ",
                                React.createElement("em", null, "Taxonomy"),
                                " selection shows an hierarchical chart ( like an org chart) of the currently selected taxonomy. This allows the user to get an overview of the currently selected taxonomy. The charts are interactive, allowing the user to hide child cells by double-clicking on parent cells. This allows for focus on selected sections of the hierarchy.")),
                        React.createElement("li", null,
                            React.createElement("p", null,
                                React.createElement("strong", null, "Monday, January 2, 2017 Budgetpedia upgrade v0.1.1 released"),
                                React.createElement("br", null),
                                "This release adds a major feature: \"select an area of interest\" which creates a \"storyboard\" of charts related to one of the main areas of budget activities, as selected by the user. This is intended to be a precursor to more configurable, narrared user storyboards in the future.")),
                        React.createElement("li", null,
                            React.createElement("p", null,
                                React.createElement("strong", null, "Tuesday, November 29, 2016 6:30-9:00 pm Budgetpedia v0.1 Launch!"),
                                React.createElement("br", null),
                                React.createElement("em", null, "Location:"),
                                " ",
                                React.createElement("a", { target: "_blank", href: "https://www.meetup.com/Civic-Tech-Toronto/events/235306439/" }, "Civic Tech Toronto Meetup")),
                            React.createElement("p", null,
                                "Join us for the official launch of Budgetpedia version 0.1 at Civic Tech's weekly meetup. See Budgetpedia in action, gain insights into the city budget and generally celebrate our going live. See the ",
                                React.createElement("a", { target: "_blank", href: "https://drive.google.com/open?id=1xZyJ6_wk4M6XP8DgrzyNi8oBvzvmzQyV6K23J0OwvZY" }, "slide deck"),
                                " for the meetup."))))));
    }
}
exports.default = Announcements;
