// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/1da639a106527e0c4010b354a1efe52a3059a291/react-props-decorators/react-props-decorators.d.ts
// Type definitions for react-props-decorators 0.1.0
// Project: https://github.com/popkirby/react-props-decorators
// Definitions by: Qubo <https://github.com/tkqubo>
// Definitions: https://github.com/borisyankov/DefinitelyTyped


declare module "react-props-decorators" {
    import * as React from 'react';

    export interface ClassDecorator {
        <TFunction extends Function>(target:TFunction): TFunction|void;
    }

    var propTypes: (map: React.ValidationMap<any>) => ClassDecorator;
    var defaultProps: (defaultProps: any) => ClassDecorator;

    export {
        propTypes,
        defaultProps
    }
}